output   = "internal/infrastructure/db/sqlboiler/"
pkgname = "models"
wipe     = true
no-tests = true

[psql]
  dbname = "db_local"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  schema = "db_local"
  blacklist = ["migrations", "other"]
  sslmode = "disable"